# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdfFunCpp_multistate <- function(Tint, Q, pi, abs, v) {
    .Call(`_miniPCH_cdfFunCpp_multistate`, Tint, Q, pi, abs, v)
}

survFunCpp_multistate <- function(Tint, Q, pi, abs, v) {
    .Call(`_miniPCH_survFunCpp_multistate`, Tint, Q, pi, abs, v)
}

hazFunCpp_multistate <- function(Tint, Q, pi, abs, v) {
    .Call(`_miniPCH_hazFunCpp_multistate`, Tint, Q, pi, abs, v)
}

cumhazFunCpp_multistate <- function(Tint, Q, pi, abs, v) {
    .Call(`_miniPCH_cumhazFunCpp_multistate`, Tint, Q, pi, abs, v)
}

pdfFunCpp_multistate <- function(Tint, Q, pi, abs, v) {
    .Call(`_miniPCH_pdfFunCpp_multistate`, Tint, Q, pi, abs, v)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_miniPCH_RcppExport_registerCCallable`)
})
